### ISSUE TITLE
Cascading issue with referred Brand Drugs field - capturing incorrectly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [willdwyer/bcbsmaissuestracker#171]
```
What steps will reproduce the problem?
1. Log on to PClient5 as a BCBSMA Administrator
2. Click on Manage Plan
 Enter search criteria:
 Effective Date - 2015
 Financial Arrangement - ASC
 Market Segment - Large Group 100+
 Product Type - EPO
 Plan Type - Standard
 Click - Show Me Plans"
3. Hover cursor over desired plan (600307HR_Advantage_Blue_80-0204LGASC1-1-15) 
to select The drop down box with 3 choices will appear
 Select Create a new plan from this plan"
4. Click on Custom Plan Button
5. Click on Common Medical Events tab
6. Go to Generic Drugs field
7. Expand Eligible Options, highlight and copy value "$10/$30/$50 retail and 
mail
8. Paste into in-network field
9. On Cascade Options field, make sure Cascade All is selected
10. Proceed to save/validate
11. Click Plan Documents, generate Final PDF with disclosures
12. On PDF, go to page 3 of 8

Actual Result:
Preferred Brand Drugs In-Network reads "$30 / retail supply or $30 / mail 
service supply"

Expected Result:
Preferred Brand Drugs In-Network should read "$30 / retail supply and mail 
service supply"

Test Case #
E2E_09

```

Original issue reported on code.google.com by `wcd82...@gmail.com` on 9 Jun 2015 at 10:34

Attachments:
- [Screen Shot 2015-06-09 at 6.33.28 PM.png](https://storage.googleapis.com/google-code-attachments/bcbsmaissuestracker/issue-171/comment-0/Screen Shot 2015-06-09 at 6.33.28 PM.png)

**Comment by willdwyer** [comment]
Hello,

This issue is being reopened, as it was discovered yesterday by one of our BEs, Lauren Erlingheuser.  This was done by generating a custom out of standard plan - HMO Blue New England Value Plus Large Group 100+.  See screenshots as there is a variance in language between Generic Drugs and Preferred Brand Drugs

![screen shot 2015-09-29 at 8 52 28 am](https://cloud.githubusercontent.com/assets/13453008/10164433/74ffdc5c-6687-11e5-97cd-6f2d97e90c4a.png)

<img width="1110" alt="1" src="https://cloud.githubusercontent.com/assets/13453008/10164454/93f2309c-6687-11e5-8cf9-eb136b4eddf8.png">

<img width="1040" alt="2" src="https://cloud.githubusercontent.com/assets/13453008/10164459/9844d276-6687-11e5-80b6-3712e36d0607.png">

![screen shot 2015-09-29 at 8 53 59 am](https://cloud.githubusercontent.com/assets/13453008/10164477/b579b1c2-6687-11e5-957e-0d3b2bbd4d0b.png)

**Comment by michparrish** [comment]
Hi Will,
I've asked Steve A to take a look at this when he gets into your office. Thank you.

**Comment by TimHeasley** [comment]
Will,
I tested in PClient5 with no issues, see attached screenshots.  Please retest.
Created a custom plan from standard plan 800262.
Thank you, Tim

https://drive.google.com/file/d/0B346D2AloIVGUTFFV1FBZmN6NHM/view?usp=sharing

**Comment by willdwyer** [comment]
Hi Tim,

I retested, and this looks fixed.  Please move to production.

Note: I generated a custom plan from standard plan 800262 in production and encountered the defect just now.  So, this was a defect in both environments.

**Comment by TimHeasley** [comment]
The configurator file has been moved to Production.  Please retest and close issue once approved. Thank you.

**Comment by willdwyer** [comment]
Hi Tim,

Unfortunately, this is still a defect.  I went to test in production, and encountered the defect (see screenshot).  Note that I tested the same plan as before (800262).  The eligible option I used from the dropdown for this field was: $10/$20/$35 retail; $10/$20/$35 mail  

![screen shot 2015-09-30 at 11 02 20 am](https://cloud.githubusercontent.com/assets/13453008/10197015/b23f70d2-6763-11e5-9c7f-4578e28c1734.png)

**Comment by TimHeasley** [comment]
Will, 
The workbooks have been updated in Production and they are ready for retest.  
Let me know if you have any questions. 
Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

I have been doing some testing on this, and came across a new defect that is somewhat related to this (being opened up as a new defect).  However, this specific cascading error has not been encountered again in production.  I will continue to do more testing tomorrow.

**Comment by willdwyer** [comment]
Hi Tim,

I retested, and this looks good.  I will close this defect now.
