### ISSUE TITLE
Account name in 2015 Custom Plan Design not displaying in header of SBC once generated - BPMS-I-12

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#232]
Hi,

See screenshots as demonstration.
![image008](https://cloud.githubusercontent.com/assets/13453008/8991827/1deb90f2-36c9-11e5-96fc-a18306b9c412.png)
![image009](https://cloud.githubusercontent.com/assets/13453008/8991830/206e3870-36c9-11e5-84bf-2c0b31d95122.png)

This can be replicated by either of the following scenarios...
1.
-Go to CL
-Go directly to plan design
-Click Edit, Manage Plan
-Select Plan Document Options
-Proceed to Generate

2.
-Go to Manage Plan interface
-Filter with search criteria
-Hover over desired plan, click Plan Document Options
-Proceed to Generate

**Comment by michparrish** [comment]
Hi Will,
Where are you expecting to see the Account Name? We only map the Plan Name into the Header, if I'm right on where you're looking. If you wanted the Account Name included, this is where the user would update the Plan Name field on the Plan Details page (if you'll recall the conversation about this duplicating in the doc naming convention when we default the Preferred Account Name + Plan Name from a couple of months ago).
![sbc header](https://cloud.githubusercontent.com/assets/13471811/8992049/62f09926-36ca-11e5-8cf7-3916460f79fe.png)

**Comment by g4gaurang** [comment]
@michparrish the issue here is that when a user goes to plan document options screen (either  directly through the plan design in CL or through the manage plan search interface with the intention to just generate the a document (without going through the editing process), in such instances, the plan naming convention does not appear on the of the screen. See red box in the screen below. 

This is not a problem when EDITING a plan through the configurator. It is a problem when user only wants to generate a document from the plan design. 

we need this fixed because the BEs usually copy and paste the naming convention when they directly save the preview PDF from the plan options screen. In this case they will not be able to.

![image](https://cloud.githubusercontent.com/assets/10272072/8992301/c7ba858c-36cb-11e5-9f36-ff161e3fdc69.png)

**Comment by michparrish** [comment]
Thank you for the clarification.
I believe the header is hardcoded to only show the name of the plan being edited, when in the configurator. Originally, we were supposed to generate all documents, Standard and Custom, through the configurator and the 'offline' process of generating from CL was supposed to be retired. This has never shown the name of plans when generated directly from CL. I can research internally to obtain more details on the original setup of the configurator and generating documents directly from CL, but I believe this is functioning as designed when generating docs directly from CL. I will confirm.

**Comment by michparrish** [comment]
Good afternoon,
I've confirmed with Product that the Doc Generator and the Editor are actually separate pieces of the configurator and the Header works with the Editor. As you know, the Header (when in the Editor) is a concatenation of fields from the plan that is being edited. This is different functionality than pulling in the name of the document that you've selected to generate documents for as laid out in the offline tool process. To get the name of the document you've selected in CL to generate docs from pulled into the header of the Doc Generation piece of the tool would be an enhancement, but this is functioning as designed.
Please let us know if you would like to submit an enhancement request for this item or if you have any further questions.
Thank you!

**Comment by g4gaurang** [comment]
@michparrish please estimate the level of effort on this request.

**Comment by michparrish** [comment]
Will do - this will need to be sent to Development for LOE, so assigned to a sprint for this work to happen. Just an FYI as this is not handled via configuration and will take longer for a response.

**Comment by willdwyer** [comment]
Hi Michelle,

Just checking for an update.  Do you have an ETA as to when this will be fixed?  Please let me know.

**Comment by michparrish** [comment]
Hi Will,
This item is not a defect, it's an enhancement as stated above. I'm checking to see when this is going to be brought up with the Dev team for consideration. I'll note once I receive a response.

**Comment by willdwyer** [comment]
Hi Michelle, have you heard back from your development team on this enhancement?

(I just went to generate an SBC, and encountered it again)

**Comment by michparrish** [comment]
You are going to continue to experience this b/c it's how the system works.
I just checked with Prod and they still need to schedule this item for a sprint to be assessed. Enhancements are behind bugs and we've had some blocker bugs (including the Gov't Website field issue yesterday) to deal with first. I will update this item with the sprint dates it will be aligned with for assessment when I have that from Product.

**Comment by michparrish** [comment]
Product informed me that this item was fixed with bug AB-146 that is going into Production tonight. I tested in pclient5 and can confirm.
I tested selecting a Standard document from CL, clicking Edit > Manage Plan > Plan Documents, and the file name is now in the header of the Doc Gen screen. I also searched on 2016 Standard plans, selected one and clicked Plan Documents and the plan name was also in the header of the Doc Gen page for that process.

Please retest in pclient5 and confirm, then we can close this item without having to go the enhancement route.
Thank you!

**Comment by willdwyer** [comment]
Hi,

I retested this via a number of different scenarios, and this appears to be fixed.  This will now be closed.
