### ISSUE TITLE
Phone number appearing in plan name header

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#236]
See screenshot(s)
![screen shot 2015-08-07 at 10 20 54 am](https://cloud.githubusercontent.com/assets/13453008/9138233/8a22ffbc-3cf0-11e5-9616-4974413abff8.png)
1. Log into Production
2. Go to Manage Plan interface
3. Search for:
   Plan Year - 2016
   Product Type - POS
   Plan Type - Standard
4. Hover over plan 800203HR_Blue_Choice_Value_Plus_80-0125LG1-1-16, create a new custom plan
5. Proceed to save/validate (enter missing fields, but don't edit anything else)
6. Proceed to generate a Draft PDF with disclosures
7. After attempting generate, click Edit Plan
8. See screenshot.  Phone number appears in place of HR job # in plan name header

Please fix globally.

**Comment by michparrish** [comment]
There seem to have been issues from the field name update last night (for the new government-required website). I have removed all versions that I created since then and followed the steps above. The phone number no longer shows in the header when I click on Edit Plan from the doc generation page. Please retest and close if found to be correct. thank you!
@willdwyer

**Comment by willdwyer** [comment]
Hi, this appears to be fixed and is now being closed.

Thanks,
