### ISSUE TITLE
Junk value appearing in plan name (#VALUE!)

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#264]
Hello,

Our BE, Carol DeVincent generated a custom Blue Care Elect plan out of standard plan  800199HR_Blue_Care_Elect_Value_Plus_80-0109LG1-1-16, and a junk value (#VALUE!) was populated where it should say BCEVP.  See screenshot below, and research.
![screen shot 2015-10-07 at 12 02 44 pm](https://cloud.githubusercontent.com/assets/13453008/10343652/c276c6b0-6cec-11e5-8928-a7d6ecc18161.png)

Thank you,

**Comment by michparrish** [comment]
Hi Will - this should be all set now. Please retry. Thanks.

**Comment by g4gaurang** [comment]
@michparrish What is the reason for the occurrence of this issue ? We and understand this happens due to an invalid argument or reference in the excel workbook but why on this plan/case ? Do you not use a IFERROR error handling mechanism ?

**Comment by michparrish** [comment]
The reason is that the 'SBC Output File Name (Optional)' field was not in the correct position on the plan design, therefore an invalid reference from the workbooks. There were a few plans that had this issue a few months ago and I thought we corrected all of them. I am running reports on all 2016 standard plan designs now and will let you know if any others were impacted.

**Comment by g4gaurang** [comment]
So you mean the code in this case was looking for value in row 3 (cell C3?) but could not find it because it was in row 4 ?

**Comment by michparrish** [comment]
essentially - the 'SBC Output File Name (Optional)' field was below the 'General' header and not above.

**Comment by michparrish** [comment]
This issue only impacted one other plan: 800301. I have updated that plan.

**Comment by willdwyer** [comment]
Hi Michelle,

I retested and this appears to be fixed.  I will close now.
