### ISSUE TITLE
Refresh button on Content Library is causing a server error

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#276]
When encountering the "Server error when navigating through CL" defect (#247) hitting the refresh button on IE10 does not make the error go away.  Please research.

**Comment by michparrish** [comment]
@kselvo01 
I thought we agreed that this was not an error - as my original and incorrect understanding of the issue was that the Refresh button was causing the Server Error. A server error page will not 'go away' if the refresh button is clicked, as the system was interrupted and needs to restart from a logout.

**Comment by TimHeasley** [comment]
Will,
Based on the comment above, can we close this issue?
Thank you,
Tim

**Comment by willdwyer** [comment]
Hi Michelle, per discussion, this defect is being closed.
