### ISSUE TITLE
Inaccuracy in search results when searching for specific user(s)

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#339]
Hello,

This defect was encountered yesterday afternoon.

I was searching for documents modified only by user Matt Rimer between 4:30PM and 5:00PM yesterday afternoon, when a document that I had last modified back in September, 2015 appeared.  Please see screenshot.

![screen shot 2016-02-23 at 5 01 17 pm](https://cloud.githubusercontent.com/assets/13453008/13292209/d3663018-dae8-11e5-80ad-cabf3c63ddd8.png)

**Comment by michparrish** [comment]
We are researching this item.

**Comment by TimHeasley** [comment]
The issue has been sent to the QA team to research and find a root cause.

**Comment by TimHeasley** [comment]
Hi Will,
Our customer support team has tested and found the following reason for the issue.

The reason why the document with Will's name was coming up in the search, is because Matt checked out the document and reverted it. When using the advanced search options and specifying a specific user's last modified documents in a specific time, the system still registers that a user modified the document even if they reverted. 

Customer support logged in as Michelle in PSHADOW, and found a random plan design. The one  used happened to have last been modified by Gaurang. I checked it out so it changed to WIP status with Michelle's name. It was then reverted it which changes it back to Gaurang's name. And then just to be sure I logged out of Michelle and into our Support BCBS username. Ran an advanced search for documents modified by Michelle Parrish today between 2:00 and 2:30. Only one document came back, the one I reverted, and it had Gaurang's name as Last Modified. 

Thanks,
Tim

**Comment by willdwyer** [comment]
Hi Tim,

I can test to confirm.

Based on your analysis above, you seem to have found the root cause of the defect (which is a good thing).  However, the system should not function in this behavior, because if a document is reverted then it should go back to having the attributes/system criteria as its old version.  Therefore, it should not show up in the search.

This will be left open, but with medium priority.

**Comment by willdwyer** [comment]
Hi Tim,

I have confirmed that this is indeed the root cause for this defect.  Even though we have identified the root cause, it is still a valid defect that will be left open until it is resolved.

**Comment by willdwyer** [comment]
I have confirmed the above, and as a result, this item is being closed.
