### ISSUE TITLE
Calculator issues - Certain Value Drugs discrepancy

### ISSUE THREAD

**Issue by willdwyer** [willdwyer/bcbsmaissuestracker#370]
Hello,

While generating the following standard 2017 plans, we noticed a discrepancy in the maternity calculations.  See screenshots below.  It appears the language of 'certain value drugs' is not being interpreted correctly through the calculator in HighRoads.  When language says "Does not apply to... certain value drugs", then the deductible does NOT apply to the Diabetes calculator, but DOES apply to the Maternity calculator (since the Maternity calculator does not use mail service supply Rx drugs amounts, only the Diabetes calculator).

Please make this fix.
![screen shot 2016-08-02 at 2 45 16 pm](https://cloud.githubusercontent.com/assets/13453008/17340917/439cc7c0-58c0-11e6-957b-aee9bc3a6055.png)

![screen shot 2016-08-02 at 2 44 11 pm](https://cloud.githubusercontent.com/assets/13453008/17340915/40ff9eb6-58c0-11e6-9469-295316a329b0.png)

**Comment by willdwyer** [comment]
Looks good in PCLIENT5, even though I randomly encountered this error once while testing.  Regardless, please move to production.

![7cc46e9a-4dc1-11e6-9a46-e3803de2d65a](https://cloud.githubusercontent.com/assets/13453008/17370968/25b901b8-596c-11e6-8e48-59ae36b2614d.png)

**Comment by markderg** [comment]
Will:  This has been updated in Pclient 5 and is ready for you to validate.

Let us know your findings.

Thx. Mark

Sent from my iPhone
Please excuse any typos and auto corrections.

Mark Der Garabedian
Director, Technical Delivery
3 Burlington Woods Drive, STE 305| Burlington, MA 01803x-apple-data-detectors://1/1
P: 781-238-5448tel:781-238-5448 | F: 781-229-2471| C: 508-776-9426tel:508-776-9426 |mdergarabedian@highroads.commailto:mdergarabedian@highroads.com
HighRoads gives organizations complete control over their health care costs and compliance
http://www.highroads.comhttp://www.highroads.com/

“The information transmitted, including attachments, is intended only for the person(s) or entity to which it is addressed and may contain confidential and/or privileged material.  Any review, retransmission, dissemination or other use of, or taking of any action in reliance upon this information by persons or entities other than the intended recipient is prohibited.  If you received this in error, please contact the sender and destroy any copies of this information.”
P Please consider the environment before printing this e-mail

On Aug 2, 2016, at 2:50 PM, willdwyer <notifications@github.com<mailto:notifications@github.com>> wrote:

Hello,

While generating the following standard 2017 plans, we noticed a discrepancy in the maternity calculations. See screenshots below. It appears the language of 'certain value drugs' is not being interpreted correctly through the calculator in HighRoads. When language says "Does not apply to... certain value drugs", then the deductible does NOT apply to the Diabetes calculator, but DOES apply to the Maternity calculator (since the Maternity calculator does not use mail service supply Rx drugs amounts, only the Diabetes calculator).

Please make this fix.
[screen shot 2016-08-02 at 2 45 16 pm]https://cloud.githubusercontent.com/assets/13453008/17340917/439cc7c0-58c0-11e6-957b-aee9bc3a6055.png

[screen shot 2016-08-02 at 2 44 11 pm]https://cloud.githubusercontent.com/assets/13453008/17340915/40ff9eb6-58c0-11e6-9469-295316a329b0.png

**Comment by willdwyer** [comment]
Mark,

Looks good in PCLIENT5, even though I randomly encountered this error once while testing. Regardless, please move to production.
![7cc46e9a-4dc1-11e6-9a46-e3803de2d65a](https://cloud.githubusercontent.com/assets/13453008/17376247/c53f785a-5982-11e6-895d-bb22791cc5bd.png)

**Comment by willdwyer** [comment]
Looks fixed.  This is closed.
